добавляет кнопки прокрутки
tatiana-borisova/team-project-js pull request #20
Opened 2021-10-14 10:32 UTC by BohdanKlymenko

добавляет кнопки прокрутки

2021-10-14 11:55 UTC, tatiana-borisova requested changes

2021-10-14 11:55 UTC, tatiana-borisova commented on src/html-partials/gallery.html
> +    <a href="#" class="link btn-scroll btn-scroll__down is-hidden">DOWN</a>
btn-scroll__top не может быть на одном уровне btn-scroll. Назови класс btn-scroll--top, то же самое с down

2021-10-14 11:55 UTC, tatiana-borisova commented on src/js/refs.js
> +  btnDown: document.querySelector('.btn-scroll__down'),
По хорошему сначала пишется что делает, а потом элемент: topBtn and downBtn

2021-10-14 11:55 UTC, tatiana-borisova commented on src/sass/components/_scrollBtn.scss
> +.btn-scroll {
При разных размерах экрана кнопка залазит на фильмы

2021-10-14 11:55 UTC, tatiana-borisova commented on src/js/scrollToTop.js
> +};
Вверх проскролливает, а вниз нет до того места, где мы были внизу

2021-10-17 16:19 UTC, BohdanKlymenko commented on src/html-partials/gallery.html
> +    <a href="#" class="link btn-scroll btn-scroll__down is-hidden">DOWN</a>
убрал эти ссылки

2021-10-19 22:31 UTC, closed without merging